apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-cm
data:
  nginx.conf: |
    server {
      listen 80 default_server;
      underscores_in_headers on;
      location / {
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:3030;
      }
    }