name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  RUN_CI:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: npm install
        run: npm install
      - name: change owenershipe
        run: sudo chown -R $USER:$GROUP /etc
      - name: run test
        run: npm test

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: RUN_CI
    env:
      DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: docker login
        run: | # log into docker hub account
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(node -pe "require('./package.json')['version']")"   
      - name: Build the Docker image # push The image to the docker hub
        run: docker build --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }} --file Dockerfile .   
      - name: Docker Push
        run: docker push $DOCKER_USER/nodejs-demo:${{ steps.get_version.outputs.version }}